[package]
name = "rocket-test"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }

fast_log = "1.7.6"

lazy_static = "1.5.0"
serde = "1.0.219"

# ORM
rbs = "4.5.25"
rbatis = "4.5.50"
rbdc-mysql = "4.5.17"

