[default]
address = "127.0.0.1"
port = 8888
log_level = "normal"

[default.shutdown]
ctrlc = true
signals = ["term", "hup"]
grace = 10
mercy = 5

[default.mysql]
host = "127.0.0.1"
port = 3306
schema = "staritor"
user = "root"
password = "123456"

[release]
address = "127.0.0.1"
port = 8000
cli_colors = false

[release.shutdown]
ctrlc = false

[release.mysql]
host = "127.0.0.1"
port = 3306
schema = "staritor"
user = "root"
password = "123456"